//
//  ModeDetectionFeatureExtractor — Extract spectral features from training WAVs
//
//  Reads WAV files generated by GenerateModeTrainingData, runs SpectralAnalyzer
//  on each, and outputs a CSV of features suitable for ML training.
//
//  Usage:
//    cd AmateurDigital/AmateurDigitalCore
//    swift run ModeDetectionFeatureExtractor > ../../../ModeClassifierTraining/training_features.csv
//    swift run ModeDetectionFeatureExtractor --data /path/to/mode_training_data
//

import Foundation
import AmateurDigitalCore

// MARK: - WAV Reader (minimal)

func readWAV(_ path: String) -> [Float]? {
    guard let data = try? Data(contentsOf: URL(fileURLWithPath: path)),
          data.count > 44,
          String(data: data[0..<4], encoding: .ascii) == "RIFF" else { return nil }

    let bitsPerSample = Int(data[34..<36].withUnsafeBytes { $0.loadUnaligned(as: UInt16.self) })
    let sampleRate = Int(data[24..<28].withUnsafeBytes { $0.loadUnaligned(as: UInt32.self) })

    // Find data chunk
    var offset = 12
    while offset + 8 < data.count {
        let chunkID = String(data: data[offset..<offset+4], encoding: .ascii) ?? ""
        let chunkSize = Int(data[offset+4..<offset+8].withUnsafeBytes { $0.loadUnaligned(as: UInt32.self) })
        if chunkID == "data" { offset += 8; break }
        offset += 8 + chunkSize
    }

    let bytesPerSample = bitsPerSample / 8
    let numFrames = (data.count - offset) / bytesPerSample
    var samples = [Float]()
    samples.reserveCapacity(numFrames)

    for i in 0..<numFrames {
        let fo = offset + i * bytesPerSample
        if bitsPerSample == 16 {
            let v = data[fo..<fo+2].withUnsafeBytes { $0.loadUnaligned(as: Int16.self) }
            samples.append(Float(v) / 32768.0)
        }
    }
    return samples
}

// MARK: - Main

let fm = FileManager.default
var dataDir = "/tmp/mode_training_data"

// Parse args
for (i, arg) in CommandLine.arguments.enumerated() {
    if arg == "--data" && i + 1 < CommandLine.arguments.count {
        dataDir = CommandLine.arguments[i + 1]
    }
}

// Read labels
let labelsPath = "\(dataDir)/labels.csv"
guard let labelsData = try? String(contentsOfFile: labelsPath, encoding: .utf8) else {
    fputs("Error: labels.csv not found at \(labelsPath)\n", stderr)
    exit(1)
}

let lines = labelsData.components(separatedBy: "\n").filter { !$0.isEmpty }
guard lines.count > 1 else {
    fputs("Error: labels.csv is empty\n", stderr)
    exit(1)
}

let analyzer = SpectralAnalyzer(sampleRate: 48000)

// CSV header
print("mode,condition,bw,flatness,peaks,topPeakPower,topPeakBW,fskPairs,fskValley,cv,duty,transitions,ook,baudRate,baudConf")

var count = 0
let total = lines.count - 1

for line in lines.dropFirst() {
    let cols = line.components(separatedBy: ",")
    guard cols.count >= 3 else { continue }

    let file = cols[0]
    let mode = cols[1]
    let condition = cols[2]

    let wavPath = "\(dataDir)/\(file)"
    guard let samples = readWAV(wavPath) else {
        fputs("Warning: failed to read \(wavPath)\n", stderr)
        continue
    }

    let features = analyzer.analyze(samples)

    let bw = Int(features.occupiedBandwidth)
    let flatness = String(format: "%.4f", features.spectralFlatness)
    let peaks = features.peaks.count
    let topPeakPower = String(format: "%.1f", features.peaks.first?.powerAboveNoise ?? 0)
    let topPeakBW = String(format: "%.1f", features.peaks.first?.bandwidth3dB ?? 0)
    let fskPairs = features.fskPairs.count
    let fskValley = features.fskPairs.filter { $0.hasValley }.count
    let cv = String(format: "%.3f", features.envelopeStats.coefficientOfVariation)
    let duty = String(format: "%.3f", features.envelopeStats.dutyCycle)
    let transitions = String(format: "%.1f", features.envelopeStats.transitionRate)
    let ook = features.envelopeStats.hasOnOffKeying ? "true" : "false"
    let baudRate = String(format: "%.2f", features.estimatedBaudRate)
    let baudConf = String(format: "%.3f", features.baudRateConfidence)

    print("\(mode),\(condition),\(bw),\(flatness),\(peaks),\(topPeakPower),\(topPeakBW),\(fskPairs),\(fskValley),\(cv),\(duty),\(transitions),\(ook),\(baudRate),\(baudConf)")

    count += 1
    if count % 500 == 0 {
        fputs("  \(count)/\(total) features extracted...\n", stderr)
    }
}

fputs("Extracted \(count) feature vectors\n", stderr)
